### PR TITLE
Add typescript typings

### LINKED ISSUE #39: Add Typescript Types
I found #3 and mocked it out a bit in my app.

**edit:** Updated to the contents of the actual .d.ts file that I am using.

**edit 2:** See my PR #41

### PR DESCRIPTION
**Pull request by jimthedev**
Closes #39.

### CODE REVIEW

**Comment by gerbenmeyer** [comment]
Nice :smile:

**Comment by jimthedev** [comment]
I just realized there are some undocumented props too. Is gutterwidth supported?

**Comment by gerbenmeyer** [comment]
Yeah, but it's not an undocumented prop, it's a context type.

**Comment by jimthedev** [comment]
Oh gotcha.

**Pull request merged**
